package Tablas;
// Generated 09-mar-2019 13:15:58 by Hibernate Tools 4.3.1



/**
 * Empleados generated by hbm2java
 */
public class Empleados  implements java.io.Serializable {


     private int id;
     private String nombre;
     private String password;

    public Empleados() {
    }

	
    public Empleados(int id) {
        this.id = id;
    }
    public Empleados(int id, String nombre, String password) {
       this.id = id;
       this.nombre = nombre;
       this.password = password;
    }
   
    public int getId() {
        return this.id;
    }
    
    public void setId(int id) {
        this.id = id;
    }
    public String getNombre() {
        return this.nombre;
    }
    
    public void setNombre(String nombre) {
        this.nombre = nombre;
    }
    public String getPassword() {
        return this.password;
    }
    
    public void setPassword(String password) {
        this.password = password;
    }




}


